spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/soat_modulo_1
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect