version: '3'

services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postech-soat-modulo-1:
    image: postech-soat-modulo-1:latest
    container_name: postech-soat-modulo-1
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: prd
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-network
    restart: always

networks:
  postgres-network:
    driver: bridge